filebeat.inputs:
  - type: filestream
    id: {{ component }}
    enabled: true
    paths:
      - {{ log_file }}
    fields:
      component: {{ component }}

output.logstash:
  hosts: ["172.31.19.240:5044"]

## Defualt
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


processors:
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version", "agent.name"]

