- name: Load MongoDB Schema
  when: schema_setup == "mongo"
  block:
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js



- name: Install Mysql client
  when: schema_setup == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.yum:
        name: mysql

    - name: Load Schema
      ansible.builtiin.shell: mysql -h {{ lookup('aws_ssm', 'dev.shipping.DB_HOST', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.shipping.db_pass', region='us-east-1' ) }} < /app/schema/${component}.sql






  if [ "${schema_setup}" ==  "mysql" ]; then
  func_print_head "install Mysql"
  yum install mysql -y &>>$log_file
  func_stat_check $?

  func_print_head "download schema"
  mysql -h mysql-dev.devops2023sk.online -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>$log_file
  func_stat_check $?
