- name: Setup Systemd Service file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service


- name: Start {{ component }} service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: true
    daemon_reload: true








#  func_systemd_setup() {
#  func_print_head "setup systemd service"
#  cp $script_path/${component}.service /etc/systemd/system/${component}.service &>>$log_file
#  func_stat_check $?
#
#  func_print_head "start the ${component} service"
#  systemctl daemon-reload &>>$log_file
#  systemctl enable ${component} &>>$log_file
#  systemctl restart ${component} &>>$log_file
#  func_stat_check $?
